#!/usr/bin/env bash

pactl unload-module module-null-sink
pactl unload-module module-rtp-send
pactl load-module module-null-sink sink_name=rtp-null format=s16be channels=2 rate=48000
pactl load-module module-rtp-send source=rtp-null.monitor destination=192.168.0.24 port=4010 mtu=320
