#!/bin/bash
if [ -n "$(xrandr | grep Virtual)" ]; then
	if [ -n "$(echo $HOST_LOCATION)" ]; then
		xrandr --newmode "1600x900_60.00" 118.25 1600 1696 1856 2112 900 903 908 934 -hsync +vsync
		xrandr --addmode Virtual-1 1600x900_60.00
		xrandr --output Virtual-1 --mode 1600x900_60.00
	else
		xrandr --output Virtual-1 --mode 1920x1080
	fi
else
	if [ -e "$(echo $HOST_LOCATION)" ]; then
		xrandr --output DP-1 --mode 1920x1080 --rate 144 --pos 0x0 --rotate inverted
		xrandr --output HDMI-2 --mode 1920x1080 --rate 144 --pos 1920x0
	fi
fi

