#!/bin/sh

# add your autostart stuffs here

DISPLAYCONFIG=$(xrandr | grep "Virtual" | awk '{print $1}')

if [ -n "$(echo $DISPLAYCONFIG)" ]; then
	if [ "$DISPLAYCONFIG" = "Virtual-1" ]; then 
		xrandr --output Virtual-1 --mode 1920x1080
	else
		xrandr --newmode "1600x900_60.00" 118.25 1600 1696 1856 2112 900 903 908 934 -hsync +vsync
		xrandr --addmode Virtual1 1600x900_60.00
		xrandr --output Virtual1 --mode 1600x900_60.00
	fi
else
	xrandr --output DP-0 --mode 1920x1080 --rate 144 --pos 0x0 --output HDMI-0 --mode 1920x1080 --rate 144 --pos 1920x0
fi

# Add Background
# xwallpaper --center ~/.wallpapers/15.png &
feh --bg-scale ~/.wallpapers/15.png &

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# Xresources
xrdb merge ~/.Xresources &

# Set Layout to Latam
# setxkbmap latam &

# Disable Screensaver
# xset -dpms s off &

# Notify
dunst -config ~/.config/dunst/dunstrc &

# Clipboard
xclip &

# Activate numlock
numlockx on &
# Run compositor
picom &

if [ -e "$(echo $DISPLAYCONFIG)" ]; then
	discord &
	nextcloud &
	mullvad-vpn &
fi
# run bar script and dwm ( do not remove this )
~/.dwm/bar/./bar.sh &
dwm
 
