#!/bin/sh

# add your autostart stuffs here

# Add Background
# xwallpaper --zoom ~/.wallpapers/15.png &
feh --bg-scale "15.png" &

# Xresources
xrdb merge ~/.Xresources &

# Set Layout to Latam
# setxkbmap latam &

# Disable Screensaver
# xset -dpms s off &

# Notify
# dunst -config ~/.config/dunst/dunstrc-dark-left &

# Clipboard
xclip &

# Activate numlock
xnumlock on &
# Run compositor
# picom &

# run bar script and dwm ( do not remove this )
~/.dwm/bar/./bar.sh &
dwm
 
