#!/bin/bash
. ~/.dwm/bar/themes/uwu

# . ~/.dwm/bar/themes/uwu

# cpu_val=$()

case $BUTTON in 
	1) notify-send cpu asd
esac

#printf "^c$darkblue^^b$black^\uf2db $(grep -o "^[^ ]*" /proc/loadavg)"
printf "^c$darkblue^^b$black^\uf2db $(top -bn1 | awk -F , '/^%Cpu/{print 100-$4}')%%"



# cpu() {
#   cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)
	
#   printf "^c$darkblue^^b$black^ \uf2db "
#   printf "^c$darkblue^^b$black^$cpu_val"
# }
